### PR TITLE
Implement user project exclusion

### PR DESCRIPTION
**Pull request by nwatson**

### CODE REVIEW

**Comment by nwatson** [comment]
Hi, any word on getting this included?

**Comment by terabyte** [comment]
Hey, sorry I left you unanswered =(

I'm not at Palantir anymore and the contact I had there is not with the company anymore either, so I'm not sure who (if anyone) is taking ownership of these projects.

I have forked everything over to my github (github.com/terabyte) including stashbot, stash-codesearch, and the stash disapproval plugin.  I have every intent to keep these up to date with Palantir's versions and push my changes back to them as long as they will take them, but if they are unresponsive I'll have to just commit to the forks and eventually put them in the marketplace as well (for free).  We'll see how that goes, I hope it does not become necessary.

FWIW, I've merged your change into my branch here:
https://github.com/terabyte/stash-codesearch-plugin

**Comment by nwatson** [comment]
Ah! That would explain it. Thanks for the response and the pointer to your fork.

**Comment by terabyte** [comment]
FYI, this has been merged into the master branch of my fork.  Thanks!

**Pull request closed without merging**
